apiVersion: eksctl.io/v1alpha5
kind: cluster
metadata:
  name: ue1eksc1a
  region: us-east-1
NodeGroups:
- name: ue1eksc1ang1 
  instanceType: t2.small
  desired: 3  
# minSize: 3
# maxSize: 6
  spot: true
  ssh:
    publicKeyName: kiiz  
